name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-macos-arm64:
    name: Build (macOS arm64)
    runs-on: macos-26
    env:
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode and Swift versions
        run: |
          xcodebuild -version || true
          swift --version || true

      - name: Build release binary
        run: |
          swift build -c release

      - name: Package binary
        run: |
          mkdir -p dist
          cp .build/release/jotty dist/jotty
          cd dist
          zip -r "jotty-${RELEASE_TAG}-macos-arm64.zip" jotty
          shasum -a 256 "jotty-${RELEASE_TAG}-macos-arm64.zip" > "jotty-${RELEASE_TAG}-macos-arm64.zip.sha256"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: |
            dist/jotty-${{ env.RELEASE_TAG }}-macos-arm64.zip
            dist/jotty-${{ env.RELEASE_TAG }}-macos-arm64.zip.sha256

  release:
    name: Create GitHub Release
    needs: [build-macos-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: ./artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/jotty-*-macos-arm64.zip
            artifacts/jotty-*-macos-arm64.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
