name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-macos-arm64:
    name: Build (macOS arm64)
    runs-on: macos-26
    env:
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build release binary
        run: swift build --arch arm64 -c release --product jotty

      - name: Package binary
        run: tar -czf jotty-${{ env.RELEASE_TAG }}-macos-arm64.tar.gz -C .build/arm64-apple-macosx/release jotty

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: jotty-${{ env.RELEASE_TAG }}-macos-arm64.tar.gz

  release:
    name: Create GitHub Release
    needs: [build-macos-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: ./artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/jotty-*-macos-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
